#Não esquecer (str,bool,float e int)
a=input('Digite alguma coisa: ')
print('O tipo primitivo deste valor é: ', type(a))
print('Só tem espaços? ',a.isspace())
print('É um número?', a.isnumeric())
print('Esta em alfabético?',a.isalpha())
print('É alphanumerico?', a.isalnum())
print('Está em Maiuscula?',a.isupper())
print('Esta minuscula?', a.islower())
print(' Está capitalizada?',a.istitle())
print('É real?', a.isalnum())